A = input('Digite algo: ')
print('O tipo primitivo de {} é {}'.format(A, type(A)))
print('{} é alfanumérico? {}'.format(A, A.isalnum()))
print('{} é alfabético? {}'.format(A, A.isalpha()))
print('{} é maiúsculo? {}'.format(A, A.isupper()))
print('{} é minúsculo? {}'.format(A, A.islower()))
print('{} é um capitalizada? {}'.format(A, A.istitle()))
print('{} é numérico? {}'.format(A, A.isnumeric()))
print('{} é um dígito? {}'.format(A, A.isdigit()))
print('{} é decimal? {}'.format(A, A.isdecimal()))
print('{} é identificador? {}'.format(A, A.isidentifier()))
print('{} pode ser impresso? {}'.format(A, A.isprintable()))
print('{} é um espaço em branco? {}'.format(A, A.isspace()))
